version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(asctime)s - %(uuid)s -  %(levelname)s - %(message)s'

filters:
  uuid:
    "()": messagebus.UUIDFilter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    filters: [uuid]
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: app.log
    filters: [uuid]
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8

loggers:
  MBus:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [console]